---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webapp-tls
  namespace: lab4
spec:
  # The name of the Secret cert-manager will create.
  # The Gateway's TLS listener references this exact name.
  secretName: webapp-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ${STUDENT_NAME}.eks.ironlabs.online
